### ISSUE TITLE
Does not work in Firefox

### ISSUE THREAD

**Issue by franciscop** [apex/gh-polls#12]
It does not display the bar on Firefox, it stays like this indefinitely:

![browser](https://user-images.githubusercontent.com/2801252/27780584-1a7998f2-5fca-11e7-8c5d-9857217e41a5.png)

Browser: Firefox 54.0 (64-bit) for Linux

Animation *seems to be supported* on Firefox though: https://caniuse.com/#feat=svg-smil (and [the example](https://leunen.me/fakesmile/) works).

Extra: it works perfectly in Chrome for Linux, so it's probably a Firefox issue.

**Comment by franciscop** [comment]
Extra: the console shows this error:

```bash
Unexpected value 0.3, 0.61, 0.355, 1.1 parsing keySplines attribute.
```

Reading [the MDN doc](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/keySplines) of keySplines we get:

```
 The values of x1 y1 x2 y2 must all be in the range 0 to 1.
```

**Comment by tj** [comment]
ahh interesting, no bounce with the 1.1 :( haha, I never use FF personally

**Comment by franciscop** [comment]
"I never use FF personally" this might happen on other browsers though.

**Comment by tj** [comment]
yea I wonder if that breaks Edge too, shame, could just check the UA string too
