### ISSUE TITLE
JS implementation for Client

### ISSUE THREAD

**Issue by pi0** [apex/gh-polls#14]
Hey! `gh-polls` is awesome 😍 However go implementation of Client makes install/usage harder for users. We may develop a js variant for client:
- Easier setup and installation from npm
- Can be integrated with CIs or Bots
- Can also work in browser, we may develop Chrome extention opening Votes right from browser

@tj If i plan helping to develop such client, do you have any advices?

**Comment by tj** [comment]
I'll add a one-line shell script later today to install from the binaries, then it'll work for everyone without `npm` etc :D, much faster to install as well. 

An extension could be cool, the API is super bare-bones right now haha :D https://github.com/tj/gh-polls/blob/master/internal/client/client.go, just `{ "options": [...] }`

**Comment by blairanderson** [comment]
FYI just found this https://gh-polls.netlify.com/

**Comment by pi0** [comment]
Closing as we already have it now :)
