### ISSUE TITLE
Little react app

### ISSUE THREAD

**Issue by tj** [apex/gh-polls#17]
For building your pollssss. Maybe chuck it up on polls.apex.sh or something.

**Comment by srph** [comment]
Currently building one but with Vue. Haven't checked the internals, but any idea why a request of `POST to https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll` gives me a CORS error?

```
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource
```

cURL and Postman works, but not XHR.

**Comment by tj** [comment]
Ah I didn't add CORS yet, I'll do that in a few minutes :D

**Comment by tj** [comment]
Almost forgot! Should be good to go now

**Comment by srph** [comment]
Thanks. It's still kinda stiff but works haha. Was a fun evening project for me.

- [Online](http://gh-polls.netlify.com/)
- [Source](https://github.com/srph/gh-polls-web)

Will push out more updates soon so it's more intuitive and less awkward.

**Comment by tj** [comment]
nice work :D love that it has sorting too, I was totally not going to add that haha
