### ISSUE TITLE
Polls is not found on system

### ISSUE THREAD

**Issue by alexanderepstein** [apex/gh-polls#20]
After installing go and running ```go get github.com/tj/gh-polls/cmd/polls``` I received no errors and everything seemed fine. But running ```polls new something something something``` returns ```polls: command not found```

**Comment by tj** [comment]
Ah $GOPATH/bin should be in the $PATH, but I should have a one-liner install script soon to use the binary releases, definitely easier than installing Go :D

**Comment by tj** [comment]
Woot and now there's http://gh-polls.netlify.com
