### ISSUE TITLE
Issue with unencoded characters

### ISSUE THREAD

**Issue by srph** [apex/gh-polls#22]
Running `polls new "HAHA % X"` returns something as expected, except that the provided links give a 500 error (for both vote and image).

Here's an example of the mentioned command:

[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM80RE4P0FZQSP165DGYJTCX/HAHA%20%25%20X)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM80RE4P0FZQSP165DGYJTCX/HAHA%20%25%20X/vote)

<sub>Notice that at the time of reporting, [this shows a broken image](https://user-images.githubusercontent.com/5093058/27844764-be0195a8-6158-11e7-845d-2c4130c520cd.png).</sub>

-----

It seems to be working just fine with spaces, though:

[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM80SBY66XNY9BDY22YY7ZAT/HAHA%20X)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM80SBY66XNY9BDY22YY7ZAT/HAHA%20X/vote)

**Comment by tj** [comment]
hmm interesting, seems like it doesn't even get routed properly, maybe trying one of the other 1000 routers I guess!

**Comment by tj** [comment]
hmMmM seems ok for me 
<img width="842" alt="screen shot 2017-07-04 at 5 32 28 pm" src="https://user-images.githubusercontent.com/25254/27845006-c5a342d6-60de-11e7-84ee-8de173ec3036.png">

**Comment by tj** [comment]
oh probably a bug in Up haha.. checking

**Comment by tj** [comment]
added `req.EscapedPath()` in my proxy, my bad haha, thanks for the report!

**Comment by tj** [comment]
woot, worked

**Comment by tj** [comment]
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM82ZR93X8SXDZ7M1B6C1WQN/Foo%20%25%20Bar)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM82ZR93X8SXDZ7M1B6C1WQN/Foo%20%25%20Bar/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM82ZR93X8SXDZ7M1B6C1WQN/Bar%20%2F%20Whatever)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM82ZR93X8SXDZ7M1B6C1WQN/Bar%20%2F%20Whatever/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM82ZR93X8SXDZ7M1B6C1WQN/Something%20&%20Here)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM82ZR93X8SXDZ7M1B6C1WQN/Something%20&%20Here/vote)

**Comment by tj** [comment]
dammit haha / is still busted
