### ISSUE TITLE
Move site to this repo / gh-polls.com

### ISSUE THREAD

**Issue by tj** [apex/gh-polls#30]
If @srph is cool with it! 

I'm using this project as a test for Up's domain stuff as well so I have https://gh-polls.com now and the API lives at https://api.gh-polls.com

**Comment by srph** [comment]
Yea, why not? :D 

Anything I'd need to do specifically?

-----

I'm not sure, but I think the web builder should go to web.gh-polls.com.

[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BT2NED7CYE2YBJEBK942HND1/Move%20to%20gh-polls.com)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BT2NED7CYE2YBJEBK942HND1/Move%20to%20gh-polls.com/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BT2NED7CYE2YBJEBK942HND1/Move%20to%20web.gh-polls.com)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BT2NED7CYE2YBJEBK942HND1/Move%20to%20web.gh-polls.com/vote)

**Comment by tj** [comment]
@srph awesome thanks! Yea web.gh-polls.com is probably a good spot. I should be able to just CNAME to the Netlify stuff actually, you'll just have to add web.gh-polls.com as the custom domain in Netlify after

**Comment by tj** [comment]
@srph woot whenever you have a minute adding app.gh-polls.com to Netlify should work

**Comment by srph** [comment]
It's [up](http://app.gh-polls.com/)!

Haven't messed around with Up yet, so I have no idea if it handles HTTPS.

I used Netlify's service to provide me a Let's Encrypt certificate - is that fine?
