### ISSUE TITLE
replace vote per IP with GitHub Reaction-based voting

### ISSUE THREAD

**Issue by vassudanagunta** [apex/gh-polls#32]
An off-the-cuff idea.

Vote per IP is not reliable. Why not use GitHub reactions? It could work as follows (I haven't worked out all the kinks):

1. Users creates an issue or new comment that will contain the poll, with temporary placeholder text. 
2. User copies the ID of the issue or comment (link behind the timestamp).
3. User sets up a poll with options same as today, except up to two negative options can be specified with a prepended `-`. A `-m` option lets voters vote for more than one option. The issue/comment ID must also be passed in. 
    ```
    $ polls new "apex/gh-polls/issues/32#issue-266896404" "Cats are cool" "Dogs are better" "Ferrets for the win" "-None of the above" "-This poll sucks"
    ```
4. gh-polls assigns each option one of the GitHub reactions. The 👎 and 😕 are reserved for negative options. 
5. The user is provided with a single Markdown SVG image to paste into a comment. It contains an embedded server call. The server makes a callback to the GitHub API in realtime to count the reactions, and a graphic is returned (but with real bars of course):
    ````
    👍 Cats are cool       [========            ]
    😄 Dogs are better     [=======             ]
    ❤️ Ferrets for the win [=                   ]
    👎 None of the above   [=====               ]
    😕 This poll sucks     [=                   ]

    Enter a reaction to vote. Voters with more than one reaction will be ignored.
    ````
5. Users vote simply by voting with a reaction.

**Comment by tj** [comment]
I'm not super worried about it, just a dumb little side project, I don't think it has to be tamper-proof, if someone wants to mess with the result then oh well haha, I doubt anyone would care enough to do that.
