### ISSUE TITLE
Poll requests limitation ?

### ISSUE THREAD

**Issue by converge** [apex/gh-polls#34]
hey guys, that's a so great tool !! thank you for it.

We're using it in InstaPy Wiki, but it's not loading all the polls, do you know why ?

https://github.com/timgrossmann/InstaPy/wiki

**Comment by tj** [comment]
Ahh yep it's throttled to prevent misuse since it's just a little side project. I'll take a look at increasing it later

**Comment by converge** [comment]
sure! thank you

**Comment by converge** [comment]
hello @tj , can you take a look on it for us ?

**Comment by tj** [comment]
should be ok now :D

**Comment by converge** [comment]
thank you so much !
