### ISSUE TITLE
POST to create a new poll fails with official domain

### ISSUE THREAD

**Issue by evenchange4** [apex/gh-polls#35]
This issue is related to https://github.com/evenchange4/gh-polls-bot/pull/11 .
Thanks for PR! I have tried new official API but it cannot work. 🙀

### Success (Origin)

```cmd
$ curl --request POST \
  --url https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll \
  --header 'content-type: application/json' \
  --data '{"options":["123"]}'

{
  "id": "01BY5HCZDXADRSJA593S2K8TQG"
}
```

### Fail case

```cmd
$ curl --request POST \
  --url https://api.gh-polls.com/poll \
  --header 'content-type: application/json' \
  --data '{"options":["123"]}'

Malformed request body.
```

**Comment by tj** [comment]
I didn't realize the web one was still using the old end-point haha, should be ok now!

**Comment by tj** [comment]
test:

[![](https://api.gh-polls.com/poll/01BY6JNCYHRXCXC8D1T9FJPC9B/foo)](https://api.gh-polls.com/poll/01BY6JNCYHRXCXC8D1T9FJPC9B/foo/vote)
[![](https://api.gh-polls.com/poll/01BY6JNCYHRXCXC8D1T9FJPC9B/bar)](https://api.gh-polls.com/poll/01BY6JNCYHRXCXC8D1T9FJPC9B/bar/vote)
[![](https://api.gh-polls.com/poll/01BY6JNCYHRXCXC8D1T9FJPC9B/baz)](https://api.gh-polls.com/poll/01BY6JNCYHRXCXC8D1T9FJPC9B/baz/vote)

**Comment by evenchange4** [comment]
Web and Bot both work great now with official domain name.
